name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.7.0
    - name: install env
      run: |
           sudo apt-get update
           sudo apt-get upgrade
           sudo apt install build-essential openjdk-8-jdk maven cmake byacc flex automake libtool-bin bison binutils-dev libiberty-dev zip unzip libncurses5-dev curl git ninja-build 
           sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
           sudo apt update
           sudo apt install gcc-10 g++-10 
           sudo apt-get install autoconf automake libtool autopoint
    - name: build
      run: |
          sudo ls
          sudo WITH_MYSQL=1 WITH_LZO=1 USE_AVX2=0 ./build.sh
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
    # Artifact name
          name: out
    # Destination path
          path: /output
